---
title: "YM-KN"
author: "Dylan Stark"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{YM-KN}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(tidyverse)
library(stringr)
library(tidytext)

library(courseraswiftkey)
```

```{r}
data("en_us_news")

ex_en <- en_us_news %>%
  head(100)

quad_en <- ex_en %>%
  unnest_tokens(quad, text, token = "ngrams", n = 4) %>%
  mutate(prefix = word(quad, 1, 3),
         word = word(quad, -1)) %>%
  select(-line, -quad)
quad_en
```

Implementation of [Kneser-Ney smoothing](https://en.wikipedia.org/wiki/Kneser%E2%80%93Ney_smoothing).

Discount: $\delta$

```{r}
delta <- 0.5
```

Discounted count of times word follows prefix: $max(c(w_{i-n+1}^{i-1}, w_i) - \delta, 0)$

```{r}
discounted_counts <- quad_en %>%
  group_by(prefix, word) %>%
  summarize(c_prefix_word = n()) %>%
  mutate(max_prefix_word = pmax(c_prefix_word - delta, 0)) %>%
  arrange(desc(c_prefix_word), prefix, word)
discounted_counts
```

Sum of counts of times any word follows prefix: $\sum_{w\prime}c(w_{i-1},w\prime)$

```{r}
all_c_prefix_any <- quad_en %>%
  group_by(prefix) %>%
  summarize(c_prefix_any = n()) %>%
  arrange(desc(c_prefix_any), prefix)
all_c_prefix_any
```

Kneser-Ney smoothed probability: $$p_{KN}(w_i | w_{i-n+1}^{i-1}) = \frac{max(c(w_{i-n+1}^{i-1}, w_i) - \delta, 0)}{\sum_{w\prime}c(w_{i-1},w\prime)}$$

```{r}
quad_en %>%
  left_join(discounted_counts, by = c("prefix", "word")) %>%
  left_join(all_c_prefix_any, by = c("prefix")) %>%
  select(-c_prefix_word) %>%
  mutate(first_term = max_prefix_word / c_prefix_any) %>%
  arrange(desc(first_term))
```


